services:
  gumuslergroup:
    build:
      context: .
    container_name: gumuslergroup
    depends_on:
      - gumuslergroupdatabase
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gumuslergroupdatabase:5432/gumuslergroup
    ports:
      - "8086:8086"
    volumes:
      - /var/www/upload:/var/www/upload
    networks:
      - mynetwork

  gumuslergroupdatabase:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres
    container_name: gumuslergroupdatabase
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gumuslergroup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 🔥 Kalıcı veri deposu ekledik
    networks:
      - mynetwork


volumes:
  postgres_data:  # 🔥 Postgres için kalıcı veri deposu
  upload-data:


networks:
  mynetwork:
    driver: bridge
